/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package event_UI;

import database.dbConnection2;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Samudi
 */
public class artistDetails extends javax.swing.JPanel {

    /**
     * Creates new form artistDetails
     */
    public static int arID=0;
    private static boolean insertAdditional ;
    private static boolean insertNew;
    private boolean alreadyExecuted=false;
    private boolean rowSelected;
    public artistDetails() {
        initComponents();
        new_arID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        pv_btn_add = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arTable = new javax.swing.JTable();
        ar_btn_remove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ar_txt_numHrs = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        ar_txt_avgCost = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ar_txt_spclNote = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ar_txt_numMem = new javax.swing.JTextField();
        ar_trans_yes = new javax.swing.JRadioButton();
        ar_trans_no = new javax.swing.JRadioButton();
        ar_ins_yes = new javax.swing.JRadioButton();
        ar_ins_no = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        ar_cmbo_genre = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ar_txt_name = new javax.swing.JTextField();
        ar_txt_phone = new javax.swing.JTextField();
        ar_txt_email = new javax.swing.JTextField();
        pv_btn_srch = new javax.swing.JButton();
        ar_btn_addNew = new javax.swing.JButton();
        ar_btn_add = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        pv_btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/navigate_right2.png"))); // NOI18N
        pv_btn_add.setToolTipText("Add");
        pv_btn_add.setBorderPainted(false);
        pv_btn_add.setContentAreaFilled(false);
        pv_btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pv_btn_add.setFocusPainted(false);
        pv_btn_add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shadow/navigate_right2.png"))); // NOI18N
        pv_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pv_btn_addActionPerformed(evt);
            }
        });

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artist Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 24))); // NOI18N
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(720, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artists", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);

        arTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        arTable.setOpaque(false);
        arTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arTable);

        ar_btn_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/forbidden.png"))); // NOI18N
        ar_btn_remove.setToolTipText("Remove");
        ar_btn_remove.setBorderPainted(false);
        ar_btn_remove.setContentAreaFilled(false);
        ar_btn_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ar_btn_remove.setFocusPainted(false);
        ar_btn_remove.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shadow/forbidden.png"))); // NOI18N
        ar_btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ar_btn_removeActionPerformed(evt);
            }
        });

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 98, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ar_btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(78, 78, 78))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ar_btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Additional Detials", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Instrument Supply :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Number of Hours :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Special Notes :");

        ar_txt_numHrs.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.5d, 24.0d, 0.5d));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Average Cost :");

        ar_txt_spclNote.setColumns(10);
        ar_txt_spclNote.setRows(3);
        jScrollPane3.setViewportView(ar_txt_spclNote);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Transport Supply:");
        jLabel1.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Number of Members :");

        buttonGroup1.add(ar_trans_yes);
        ar_trans_yes.setText("Yes");
        ar_trans_yes.setOpaque(false);

        buttonGroup1.add(ar_trans_no);
        ar_trans_no.setText("No");
        ar_trans_no.setOpaque(false);

        buttonGroup2.add(ar_ins_yes);
        ar_ins_yes.setText("Yes");
        ar_ins_yes.setOpaque(false);

        buttonGroup2.add(ar_ins_no);
        ar_ins_no.setText("No");
        ar_ins_no.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Genre :");

        ar_cmbo_genre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose One", "Alternative Music", "Blues", "Classical Music", "Country Music", "Children's Music", "Dance Music", "Easy Listening", "Electronic Music", "European Music (Folk / Pop)", "Hip Hop / Rap", "Indie Pop", "Inspirational (incl. Gospel)", "Asian Pop (J-Pop, K-pop)", "Jazz", "Latin Music", "Metal ", "New Age", "Opera", "Pop (Popular music)", "R&B / Soul", "Reggae", "Rock", "Singer / Songwriter (inc. Folk)", "World Music / Beats", "Other" }));
        ar_cmbo_genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ar_cmbo_genreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel10))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(ar_trans_yes)
                                        .addGap(18, 18, 18)
                                        .addComponent(ar_trans_no))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(ar_ins_yes)
                                        .addGap(18, 18, 18)
                                        .addComponent(ar_ins_no)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ar_cmbo_genre, 0, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ar_txt_numMem, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ar_txt_numHrs, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ar_txt_avgCost, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(148, 148, 148))
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ar_trans_yes)
                    .addComponent(ar_trans_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ar_ins_yes)
                    .addComponent(ar_ins_no))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ar_cmbo_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ar_txt_numMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ar_txt_numHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(ar_txt_avgCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Name :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Phone :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Email :");

        pv_btn_srch.setText("Search");
        pv_btn_srch.setToolTipText("Search");
        pv_btn_srch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pv_btn_srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pv_btn_srchActionPerformed(evt);
            }
        });

        ar_btn_addNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        ar_btn_addNew.setToolTipText("Add New");
        ar_btn_addNew.setBorderPainted(false);
        ar_btn_addNew.setContentAreaFilled(false);
        ar_btn_addNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ar_btn_addNew.setFocusPainted(false);
        ar_btn_addNew.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shadow/add.png"))); // NOI18N
        ar_btn_addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ar_btn_addNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pv_btn_srch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ar_btn_addNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addComponent(ar_txt_phone)
                    .addComponent(ar_txt_name)
                    .addComponent(ar_txt_email))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ar_btn_addNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pv_btn_srch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ar_txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ar_txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ar_txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ar_btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/navigate_right2.png"))); // NOI18N
        ar_btn_add.setToolTipText("Add");
        ar_btn_add.setBorderPainted(false);
        ar_btn_add.setContentAreaFilled(false);
        ar_btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ar_btn_add.setFocusPainted(false);
        ar_btn_add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shadow/navigate_right2.png"))); // NOI18N
        ar_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ar_btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(ar_btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(ar_btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void arTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arTableMouseClicked
        fillTextFields(Integer.parseInt(String.valueOf(arTable.getValueAt(arTable.getSelectedRow(), 0))));      
        fillAdditionalDetails(eventDetails.eventID , Integer.parseInt( String.valueOf(arTable.getValueAt(arTable.getSelectedRow(), 0))));
        insertNew=false;
        insertAdditional=false;
        rowSelected=true;
    }//GEN-LAST:event_arTableMouseClicked

    private void pv_btn_srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pv_btn_srchActionPerformed
        searchArtist jfw = new searchArtist();
        jfw.setVisible(true);
    }//GEN-LAST:event_pv_btn_srchActionPerformed

    private void ar_btn_addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ar_btn_addNewActionPerformed
        clear();
        new_arID();
         
        insertNew=true;
        insertAdditional=true;    //an event can have many artists
    }//GEN-LAST:event_ar_btn_addNewActionPerformed

    private void pv_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pv_btn_addActionPerformed
       
    }//GEN-LAST:event_pv_btn_addActionPerformed

    private void ar_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ar_btn_addActionPerformed
        update_eventArtistTable();
         if(!alreadyExecuted){
            event_mainWindow.updateProgressBar(15);
            alreadyExecuted=true;
        }
        int rowSelected = arTable.getSelectedRow();         //do not fill arTable again while ar table row selected
            
            if(rowSelected == -1)
                fillArTable();
            
        new_arID();
        clear();   
    }//GEN-LAST:event_ar_btn_addActionPerformed

    private void ar_cmbo_genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ar_cmbo_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ar_cmbo_genreActionPerformed

    private void ar_btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ar_btn_removeActionPerformed
        // TODO add your handling code here:
         if(!rowSelected){
            JOptionPane.showMessageDialog(null, "Please Select an Event...!","Error",1);
        }else{
            if(JOptionPane.showConfirmDialog(null,"Are You sure want to Remove this...?","Remove",JOptionPane.YES_NO_OPTION)==0){
               try {
                    Statement con = dbConnection2.db().createStatement();
                    con.executeUpdate("DELETE FROM eventartists WHERE eventID='"+eventDetails.eventID+"'");
                    
                    DefaultTableModel table = (DefaultTableModel) arTable.getModel();
                    table.removeRow(arTable.getSelectedRow());
                } catch (ClassNotFoundException | SQLException | HeadlessException e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_ar_btn_removeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ViewReport vr = new ViewReport("./reports/report_ar.jasper");
        vr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public static void fillTextFields(int t_arID){
        arID=t_arID;
        insertNew=false;
              try{
                Statement con = dbConnection2.db().createStatement();
                ResultSet record =  con.executeQuery("SELECT * FROM artistsdetails WHERE arID='"+arID+"'" );
                   while(record.next()){
                        ar_txt_name.setText(record.getString("ar_name"));
                        ar_txt_phone.setText(record.getString("ar_phone"));
                        ar_txt_email.setText(record.getString("ar_email"));
                    }
            }catch (ClassNotFoundException | SQLException ex) {
                  System.out.println(ex);
        }
    }
    
    private void fillAdditionalDetails(int t_eventID , int t_arID){
        
        int tranSup=0,instSup=0;

        try{
                Statement con = dbConnection2.db().createStatement();
                ResultSet record =  con.executeQuery("SELECT * FROM eventartists WHERE arID='"+t_arID+"' AND eventID='"+t_eventID+"'" );
                   while(record.next()){
                        ar_txt_avgCost.setText(record.getString("avgCost"));
                        ar_txt_spclNote.setText(record.getString("spclNote"));
                        ar_txt_numHrs.setValue(Double.parseDouble(record.getString("numOfhours")));
                        ar_txt_numMem.setText(record.getString("numOfmembers"));
                        tranSup= Integer.parseInt(record.getString("transportSupply"));
                        instSup = Integer.parseInt(record.getString("instrumentSupply"));
                        ar_cmbo_genre.setSelectedItem(record.getString("genre"));
                    }
            }catch (ClassNotFoundException | SQLException ex) {
               System.out.println(ex);
        }

        if(tranSup==1)
            ar_trans_yes.setSelected(true);
        else
            ar_trans_no.setSelected(true);
        
        if(instSup==1)
            ar_ins_yes.setSelected(true);
        else
            ar_ins_no.setSelected(false);
    }
    
    private boolean isTextFiledNull(JTextField t){
        return t.getText().equals("") || t.getText() == null;
    }
    
    private boolean nullValidate(){

        if(isTextFiledNull(ar_txt_avgCost))
            return false;
        else if(isTextFiledNull(ar_txt_name))
            return false;
        else if(isTextFiledNull(ar_txt_phone))
            return false;
        else 
            return true;
        
    }
    
     private boolean isValidMoblieNo(JTextField t){
        return t.getText().length()==10;
    }
    
    private void new_arID(){
        try{
            Statement con = dbConnection2.db().createStatement();
            java.sql.ResultSet record1  = con.executeQuery("SELECT MAX(arID)+1 FROM artistsdetails");      //get next venue ID
                while(record1.next()){                                                                          // if there is not already inserted venue
                    if(record1.getString(1) == null)                                                            // venue id set to 1  
                        arID = 1;
                    else
                        arID = Integer.parseInt(record1.getString("MAX(arID)+1"));                            // else set venue id to next number
                }
        }catch(ClassNotFoundException | SQLException | NumberFormatException e){
                System.out.println(e);
        }
        
        insertNew=true;
        insertAdditional=true;
    }
        
    private void fillArTable(){

        DefaultTableModel table = (DefaultTableModel) arTable.getModel();
       // table.setRowCount(0);
        
        //setting column width
        TableColumnModel columnModel = arTable.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(1).setPreferredWidth(150);
        try {
            Statement con = dbConnection2.db().createStatement();
            java.sql.ResultSet record =  con.executeQuery("SELECT arID,ar_name FROM artistsdetails WHERE arID='"+arID+"' " );
                while(record.next()){   
                    Vector rc = new Vector();
                    rc.add(record.getString("arID"));
                    rc.add(record.getString("ar_name"));
                    table.addRow(rc);
                }
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }
    } 
        
        
     private void update_eventArtistTable(){
        int tranSup = ar_trans_yes.isSelected() ? 1:0;
        int instSup = ar_ins_yes.isSelected() ? 1:0;
         
         if(!nullValidate()){
            JOptionPane.showMessageDialog(null,"Field Cannot be Empty...!","Error",1);
        }else if(!isValidMoblieNo(ar_txt_phone)){
            JOptionPane.showMessageDialog(null,"Moblie Number is Invalid...!","Error",1);
            ar_txt_phone.grabFocus();
        }else {
         try{
            Statement con = dbConnection2.db().createStatement();  
                if(insertNew){
                    
                    con.executeUpdate("INSERT INTO artistsdetails "
                                      +"VALUES('"+arID+"' , '"+ar_txt_name.getText()+"' , '"+ar_txt_phone.getText()+"' , '"+ar_txt_email.getText()+"') ");
                    
                    con.executeUpdate("INSERT INTO eventartists VALUES('"+eventDetails.eventID+"', '"+arID+"' , '"+tranSup+"' ,"
                                         +" '"+instSup+"' , '"+ar_cmbo_genre.getSelectedItem()+"' , '"+String.valueOf(ar_txt_numHrs.getValue())+"' , '"+ar_txt_numMem.getText()+"' , '"+ar_txt_avgCost.getText()+"' , '"+ar_txt_spclNote.getText()+"') ");
                    insertNew=false;
                    
                }else{
                    
                    con.executeUpdate("UPDATE artistsdetails "
                                     +"SET ar_name='"+ar_txt_name.getText()+"' , ar_phone='"+ar_txt_phone.getText()+"' , ar_email='"+ar_txt_email.getText()+"' "
                                     +"WHERE arID='"+arID+"' ");
                    
                  //insert additional details
                    if(insertAdditional){
                        con.executeUpdate("INSERT INTO eventartists VALUES('"+eventDetails.eventID+"', '"+arID+"' , '"+tranSup+"' ,"
                                         +"'"+instSup+"' , '"+ar_cmbo_genre.getSelectedItem()+"' , '"+String.valueOf(ar_txt_numHrs.getValue())+"' , '"+ar_txt_numMem.getText()+"' , '"+ar_txt_avgCost.getText()+"' , '"+ar_txt_spclNote.getText()+"') ");
                        insertAdditional = false;
                    //update additional details    
                    }else{                                                 
                        con.executeUpdate("UPDATE eventartists SET transportSupply= '"+tranSup+"' , instrumentSupply='"+instSup+"' , genre='"+ar_cmbo_genre.getSelectedItem()+"' , "
                                         +" numOfhours='"+String.valueOf(ar_txt_numHrs.getValue())+"' , numOfmembers='"+ar_txt_numMem.getText()+"' , avgCost='"+ar_txt_avgCost.getText()+"' , spclNote='"+ar_txt_spclNote.getText()+"' WHERE eventID='"+eventDetails.eventID+"' AND arID='"+arID+"' ");
                    }
                }
            }catch(ClassNotFoundException | SQLException | HeadlessException e){
                        System.out.println(e);
            }  
        }
    }    
        
        
     
    private void clear(){
        ar_txt_name.setText("");
        ar_txt_phone.setText("");
        ar_txt_email.setText("");
        ar_txt_avgCost.setText("");
        ar_txt_numMem.setText("");
        ar_txt_spclNote.setText("");
        ar_trans_yes.setSelected(false);
        ar_trans_no.setSelected(false);
        ar_ins_yes.setSelected(false);
        ar_trans_no.setSelected(false);
        ar_cmbo_genre.setSelectedItem("Choose One");
        
        arTable.clearSelection();
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable arTable;
    private javax.swing.JButton ar_btn_add;
    private javax.swing.JButton ar_btn_addNew;
    private javax.swing.JButton ar_btn_remove;
    private javax.swing.JComboBox ar_cmbo_genre;
    private javax.swing.JRadioButton ar_ins_no;
    private javax.swing.JRadioButton ar_ins_yes;
    private javax.swing.JRadioButton ar_trans_no;
    private javax.swing.JRadioButton ar_trans_yes;
    private javax.swing.JTextField ar_txt_avgCost;
    private static javax.swing.JTextField ar_txt_email;
    private static javax.swing.JTextField ar_txt_name;
    private javax.swing.JSpinner ar_txt_numHrs;
    private javax.swing.JTextField ar_txt_numMem;
    private static javax.swing.JTextField ar_txt_phone;
    private javax.swing.JTextArea ar_txt_spclNote;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton pv_btn_add;
    private javax.swing.JButton pv_btn_srch;
    // End of variables declaration//GEN-END:variables
}
