/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event_UI;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Dhanuka Abeywardhane
 */
public class event_mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form event_mainWindow
     */
    
    eventDetails event = new eventDetails();
    Venue venue = new Venue();
    caterDetails cater = new caterDetails();
    decorationDetails deco = new decorationDetails();
    photographerDetails photo = new photographerDetails();
    artistDetails artist = new artistDetails();
    TimeLine timeLine = new TimeLine();
    
    MyEvents myEvents = new MyEvents();
 
    public event_mainWindow() {
        
        initComponents();
        hidePrevNextBtns();
        jProgressBar1.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evt_main_nxtBtn = new javax.swing.JButton();
        evt_main_prevBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        mainNavWindow = new javax.swing.JPanel();
        evt_main_evtDetails = new javax.swing.JButton();
        evt_main_myEvnts = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("tab_sel_border"));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 650));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        evt_main_nxtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_right_blue.png"))); // NOI18N
        evt_main_nxtBtn.setToolTipText("Next");
        evt_main_nxtBtn.setBorderPainted(false);
        evt_main_nxtBtn.setContentAreaFilled(false);
        evt_main_nxtBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        evt_main_nxtBtn.setFocusPainted(false);
        evt_main_nxtBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shadow/arrow_right_blue.png"))); // NOI18N
        evt_main_nxtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evt_main_nxtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(evt_main_nxtBtn);
        evt_main_nxtBtn.setBounds(660, 60, 30, 30);

        evt_main_prevBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_left_blue.png"))); // NOI18N
        evt_main_prevBtn.setToolTipText("Previous");
        evt_main_prevBtn.setBorderPainted(false);
        evt_main_prevBtn.setContentAreaFilled(false);
        evt_main_prevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        evt_main_prevBtn.setFocusPainted(false);
        evt_main_prevBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shadow/arrow_left_blue.png"))); // NOI18N
        evt_main_prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evt_main_prevBtnActionPerformed(evt);
            }
        });
        getContentPane().add(evt_main_prevBtn);
        evt_main_prevBtn.setBounds(610, 60, 30, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/navigate_cross.png"))); // NOI18N
        jButton1.setToolTipText("Exit");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shadow/navigate_cross.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 10, 30, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/navigate_minus.png"))); // NOI18N
        jButton2.setToolTipText("Minimize");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shadow/navigate_minus.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(710, 20, 30, 20);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(102, 255, 102));
        jProgressBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(200, 60, 403, 30);

        jLabel2.setBackground(new java.awt.Color(204, 51, 0));
        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 30)); // NOI18N
        jLabel2.setText("Event Planner Pro");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 350, 31);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/unknown.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shadow/unknown.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(670, 10, 30, 30);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(750, 550));

        mainNavWindow.setOpaque(false);
        mainNavWindow.setPreferredSize(new java.awt.Dimension(700, 500));

        evt_main_evtDetails.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        evt_main_evtDetails.setText("Plan an Event");
        evt_main_evtDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        evt_main_evtDetails.setContentAreaFilled(false);
        evt_main_evtDetails.setFocusPainted(false);
        evt_main_evtDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                evt_main_evtDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                evt_main_evtDetailsMouseExited(evt);
            }
        });
        evt_main_evtDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evt_main_evtDetailsActionPerformed(evt);
            }
        });

        evt_main_myEvnts.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        evt_main_myEvnts.setText("My Events");
        evt_main_myEvnts.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        evt_main_myEvnts.setContentAreaFilled(false);
        evt_main_myEvnts.setFocusPainted(false);
        evt_main_myEvnts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                evt_main_myEvntsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                evt_main_myEvntsMouseExited(evt);
            }
        });
        evt_main_myEvnts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evt_main_myEvntsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainNavWindowLayout = new javax.swing.GroupLayout(mainNavWindow);
        mainNavWindow.setLayout(mainNavWindowLayout);
        mainNavWindowLayout.setHorizontalGroup(
            mainNavWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainNavWindowLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(evt_main_evtDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(evt_main_myEvnts, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        mainNavWindowLayout.setVerticalGroup(
            mainNavWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainNavWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainNavWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(evt_main_myEvnts, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(evt_main_evtDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(mainNavWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(mainNavWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jLayeredPane1.setLayer(mainNavWindow, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(30, 100, 720, 550);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 680);

        getAccessibleContext().setAccessibleParent(this);

        setSize(new java.awt.Dimension(788, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void evt_main_prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evt_main_prevBtnActionPerformed
        if(myEvents.isVisible()){
           hidePanel(myEvents);
           showMainNavigation();
       } 
        
        if(timeLine.isVisible()){
            showPanel(artist);
            hidePanel(timeLine);
       }else if(artist.isVisible()){
           showPanel(photo);
           hidePanel(artist);
       }else if(photo.isVisible()){
           showPanel(deco);
           hidePanel(photo);
       }else if(deco.isVisible()){
            showPanel(cater);
            hidePanel(deco);
       }else if(cater.isVisible()){
           showPanel(venue);
           hidePanel(cater);
       }else if(venue.isVisible()){
           showPanel(event);
           hidePanel(venue);
       }else if(event.isVisible()){
           hidePanel(event);
           showMainNavigation();
       }  
    }//GEN-LAST:event_evt_main_prevBtnActionPerformed

    private void evt_main_nxtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evt_main_nxtBtnActionPerformed
        if(eventDetails.eventID == 0){
            JOptionPane.showMessageDialog(null, "Please Fill Data to go next step...!");
        }else{
        
            if(event.isVisible()){
                showPanel(venue);
                hidePanel(event);
            }else if(venue.isVisible()){
                showPanel(cater);
                hidePanel(venue);
            }else if(cater.isVisible()){
                showPanel(deco);
                hidePanel(cater);
            }else if(deco.isVisible()){
                showPanel(photo);
                hidePanel(deco);
            }else if(photo.isVisible()){
                showPanel(artist);
                hidePanel(photo);
            }else if(artist.isVisible()){
                showPanel(timeLine);
                timeLine.updateTimeLineName();      //calling method in timeline
                hidePanel(artist);
            }
        
        }
    }//GEN-LAST:event_evt_main_nxtBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(JOptionPane.showConfirmDialog(null,"Are You sure want to Log out...?","Logout",JOptionPane.YES_NO_OPTION)==0){
       try{
        login log = new login();
        log.setVisible(true);
        this.dispose();
        }catch (Exception ex){
            ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(event_mainWindow.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void evt_main_evtDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evt_main_evtDetailsActionPerformed

       addAllJPane();
       showPrevNextBtns();
       jProgressBar1.setVisible(true);
       hideAll();
       hidePanel(mainNavWindow);
       showPanel(event);
    }//GEN-LAST:event_evt_main_evtDetailsActionPerformed
    public void test(java.awt.event.ActionEvent evt){
        evt_main_evtDetailsActionPerformed(evt);
    }
    
    public void addAllJPane(){
       jLayeredPane1.add(event);
       jLayeredPane1.add(venue);
       jLayeredPane1.add(cater);
       jLayeredPane1.add(deco);
       jLayeredPane1.add(photo);
       jLayeredPane1.add(artist);
       jLayeredPane1.add(timeLine);
    }
    
    private void evt_main_myEvntsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evt_main_myEvntsActionPerformed
        jLayeredPane1.add(myEvents);
        hidePanel(mainNavWindow);
        showPanel(myEvents);
        showPrevNextBtns();
        evt_main_nxtBtn.setEnabled(false);
       
    }//GEN-LAST:event_evt_main_myEvntsActionPerformed

    private void evt_main_evtDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evt_main_evtDetailsMouseEntered
        setBevelBorder(evt_main_evtDetails);
    }//GEN-LAST:event_evt_main_evtDetailsMouseEntered

    private void evt_main_evtDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evt_main_evtDetailsMouseExited
        setSoftBevelBorder(evt_main_evtDetails);
    }//GEN-LAST:event_evt_main_evtDetailsMouseExited

    private void evt_main_myEvntsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evt_main_myEvntsMouseEntered
        setBevelBorder(evt_main_myEvnts);
    }//GEN-LAST:event_evt_main_myEvntsMouseEntered

    private void evt_main_myEvntsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evt_main_myEvntsMouseExited
        setSoftBevelBorder(evt_main_myEvnts);
    }//GEN-LAST:event_evt_main_myEvntsMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           try {
            Desktop.getDesktop().open(new File("manual.pdf"));
        } catch (IOException ex) {
               System.out.println(ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    //user defined methods
    private void setBevelBorder(JButton b){
        b.setBorder(BorderFactory.createBevelBorder(0));
    }
    private void setSoftBevelBorder(JButton b){
        b.setBorder(BorderFactory.createSoftBevelBorder(0));
    }
    private void hidePrevNextBtns(){
        evt_main_nxtBtn.setVisible(false);
        evt_main_prevBtn.setVisible(false);
    }
    
    public void showPrevNextBtns(){
        evt_main_nxtBtn.setVisible(true);
        evt_main_prevBtn.setVisible(true);
        evt_main_nxtBtn.setEnabled(true);
    }
    
    public void showPanel(JPanel j){
        j.setSize(720,550);
        j.setVisible(true);
        jLayeredPane1.moveToFront(j);
        //System.out.println("SHOW");
    }
    
    public void hidePanel(JPanel j){
        j.setVisible(false);
        //System.out.println("HIDE");
    }
    public void hideAll(){
        event.setVisible(false);
        venue.setVisible(false);
        cater.setVisible(false);
        deco.setVisible(false);
        photo.setVisible(false);
        artist.setVisible(false);
        timeLine.setVisible(false);
        
        myEvents.setVisible(false);
    }
    
    private void showMainNavigation(){
        
        jLayeredPane1.remove(event);
        jLayeredPane1.remove(venue);
        jLayeredPane1.remove(cater);
        jLayeredPane1.remove(deco);
        jLayeredPane1.remove(photo);
        jLayeredPane1.remove(artist);
        jLayeredPane1.remove(timeLine);
        
        jLayeredPane1.remove(myEvents);
        
        mainNavWindow.setVisible(true);
        jLayeredPane1.moveToFront(mainNavWindow);
        
        hidePrevNextBtns();
        jProgressBar1.setVisible(false);
    }
    
    private static int sumValue = 0;
    public static void updateProgressBar(int value){
        sumValue+=value; 
        jProgressBar1.setValue(sumValue);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(event_mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(event_mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(event_mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(event_mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new event_mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton evt_main_evtDetails;
    public javax.swing.JButton evt_main_myEvnts;
    private javax.swing.JButton evt_main_nxtBtn;
    private javax.swing.JButton evt_main_prevBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLayeredPane jLayeredPane1;
    public static javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JPanel mainNavWindow;
    // End of variables declaration//GEN-END:variables

   
}
