/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * loginrec.java
 *
 * Created on Jul 16, 2013, 11:51:56 PM
 */
package event_UI;


import database.dbConnection2;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;


import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author HP
 */
public class login extends javax.swing.JFrame {

    String al, pw, un = "null";
   
   

    /** Creates new form loginrec */
    public login() {
        try {
            //logintime.setVisible(false);
            //logindate.setVisible(false);
            initComponents();
            
           
            
            
         /* try {
                UIManager.setLookAndFeel(new SubstanceRavenGraphiteGlassLookAndFeel());
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(loginrec.class.getName()).log(Level.SEVERE, null, ex);
            }*/
             new Thread(new Runnable() {
    //UIManager.setLookAndFeel(new SubstanceRavenGraphiteGlassLookAndFeel());
                    public void run() {
                        while(true){
                            Date d = new Date();
                            String date = d.toString();
                            String ar[] = date.split(" ");
                            time.setText(ar[3]);
                        }
                    }
                }).start();

    //UIManager.setLookAndFeel(new SubstanceRavenGraphiteGlassLookAndFeel());
            capslocklable.setVisible(false);
            passwordlable.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginusername = new javax.swing.JTextField();
        loginpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        capslocklable = new javax.swing.JLabel();
        passwordlable = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event Planner Pro | Login");
        setMinimumSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        loginusername.setName("txtusername"); // NOI18N
        loginusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginusernameActionPerformed(evt);
            }
        });
        loginusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginusernameFocusGained(evt);
            }
        });
        loginusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginusernameKeyReleased(evt);
            }
        });
        getContentPane().add(loginusername);
        loginusername.setBounds(210, 70, 140, 30);

        loginpassword.setName("txtpassword"); // NOI18N
        loginpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginpasswordActionPerformed(evt);
            }
        });
        loginpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginpasswordFocusLost(evt);
            }
        });
        loginpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginpasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loginpasswordKeyTyped(evt);
            }
        });
        getContentPane().add(loginpassword);
        loginpassword.setBounds(210, 120, 140, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Password");
        jLabel2.setName("lblpassword"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 120, 90, 30);

        loginbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn.setName("btnlogin"); // NOI18N
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn);
        loginbtn.setBounds(230, 210, 92, 34);

        capslocklable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        capslocklable.setForeground(new java.awt.Color(0, 51, 255));
        capslocklable.setText("CapsLock is On");
        getContentPane().add(capslocklable);
        capslocklable.setBounds(70, 170, 110, 30);

        passwordlable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordlable.setForeground(new java.awt.Color(255, 0, 0));
        passwordlable.setText("Invalid Password...!");
        getContentPane().add(passwordlable);
        passwordlable.setBounds(220, 170, 130, 30);

        time.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(time);
        time.setBounds(10, 250, 100, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("RSPOS V1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 250, 60, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("User name");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setName("lblusername"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 70, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 450, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginusernameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_loginusernameActionPerformed

    private void loginpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginpasswordActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_loginpasswordActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        sve();
}//GEN-LAST:event_loginbtnActionPerformed

    private void loginusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginusernameFocusGained
    }//GEN-LAST:event_loginusernameFocusGained

    private void loginpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginpasswordFocusGained
       
    }//GEN-LAST:event_loginpasswordFocusGained

    private void loginpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginpasswordFocusLost
       
    }//GEN-LAST:event_loginpasswordFocusLost

    private void loginpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginpasswordKeyTyped
       boolean isCapsLockOn = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);

        if (isCapsLockOn) {
            capslocklable.setVisible(true);
        } else if (!isCapsLockOn) {
            capslocklable.setVisible(false);
        }
        if (evt.getKeyChar() == 10) {
            sve();

        }
    }//GEN-LAST:event_loginpasswordKeyTyped

    private void loginusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginusernameKeyReleased
        if (evt.getKeyChar() == 10) {
            loginpassword.grabFocus();
        }
    }//GEN-LAST:event_loginusernameKeyReleased

    private void loginpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginpasswordKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginpasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(event_mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(event_mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(event_mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(event_mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel capslocklable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField loginpassword;
    private javax.swing.JTextField loginusername;
    private javax.swing.JLabel passwordlable;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

    public void sve() {
        try {
            Statement con = dbConnection2.db().createStatement();
            ResultSet record = con.executeQuery("SELECT username,password FROM system_login WHERE username='" + loginusername.getText() + "'");
            while (record.next()) {
                un = record.getString("username");
                pw = record.getString("password");           
            }
            
             if (pw.equals(loginpassword.getText()) ) {
                
                event_mainWindow mww = new event_mainWindow();
                mww.setVisible(true);
                this.dispose();

            } else {
               // JOptionPane.showMessageDialog(null, "Invalid Password");
                passwordlable.setVisible(true);
                loginpassword.setText("");
 
            }
        } catch (Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            //ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Invalid Username");
            loginusername.setText("");
            loginusername.grabFocus(); 
}
    }

}
